light:
  - platform: artnet_led
    host: 192.168.1.35
    max_fps: 40
    node_type: sacn
    universes:
      1:
        send_partial_universe: False
        devices:
          - channel: 1
            name: Back lights
            type: dimmer
            transition: 0.5
          - channel: 2
            name: Front left
            type: dimmer
          - channel: 3
            name: Front middle
            type: dimmer
            transition: 0.5
          - channel: 4
            name: Front right
            type: dimmer
            transition: 0.5
          - channel: 6
            name: Back Far L&R
            type: dimmer
            transition: 0.5
          - channel: 7
            name: Back left
            type: dimmer
            transition: 0.5
          - channel: 8
            name: Back right
            type: dimmer
            transition: 0.5
          - channel: 13
            name: Red LED
            type: rgb
            transition: 1


logger:
  default: info
  logs:
    custom_components.artnet_led: info
    pyartnet: debug

scene:
  - name: Romantic
    icon: "mdi:flower-tulip"
    entities:
      light.test_light:
        state: "on"
        brightness: 200
        transition: 10
  - name: Movies
    entities:
      light.test_light:
        state: "on"
        brightness: 0
        transition: 10

debugpy:


homeassistant:
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 0.0.0.0/0
      allow_bypass_login: true


# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
#tts:
#  - platform: google_translate

#automation: !include automations.yaml
#script: !include scripts.yaml
#scene: !include scenes.yaml
