light:
  - platform: artnet_led
    host: 192.168.1.15
    max_fps: 43
    refresh_every: 0
    node_type: artnet-controller
    universes:
      0:
        send_partial_universe: True
        output_correction: quadratic
        devices:
#          - channel: 13
#            name: Test light
#            type: color_temp
#            transition: 0
#            channel_size: 16bit
#            min_temp: 2500K
#            max_temp: 6500K
          - channel: 1
            name: Test light RGB
            type: rgb
            transition: 0
            channel_size: 16bit

homeassistant:
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 0.0.0.0/0
      allow_bypass_login: true


# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
#tts:
#  - platform: google_translate

#automation: !include automations.yaml
#script: !include scripts.yaml
#scene: !include scenes.yaml
