light:
  - platform: artnet_led
    host: 192.168.1.15
    max_fps: 43
    refresh_every: 0
    node_type: artnet-controller
    universes:
      0:
        send_partial_universe: True
        output_correction: quadratic
        devices:
          - channel: 13
            name: Test light
            type: color_temp
            transition: 1
            channel_size: 16bit
#            min_temp: 2500K
#            max_temp: 6500K
          - channel: 1
            name: snack_bar_sign
            type: rgb
            channel_setup:
              - d
              - 1
              - 125
              - R
              - G
              - B
            output_correction: linear
            channel_size: 8bit
#          - channel: 30
#            name: Test light DOS
#            type: binary
#            channel_size: 8bit

logger:
  default: info
  logs:
    custom_components.artnet_led: info
    pyartnet: debug

scene:
  - name: Romantic
    icon: "mdi:flower-tulip"
    entities:
      light.test_light:
        state: "on"
        brightness: 200
        transition: 10
  - name: Movies
    entities:
      light.test_light:
        state: "on"
        brightness: 0
        transition: 10

debugpy:


homeassistant:
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 0.0.0.0/0
      allow_bypass_login: true


# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
#tts:
#  - platform: google_translate

#automation: !include automations.yaml
#script: !include scripts.yaml
#scene: !include scenes.yaml
