site_name: Art-net LED Lighting for DMX
theme:
  name: material
  palette:
    - scheme: slate
      primary: deep purple
      accent: lime

nav:
  - Overview: index.md
  - Configuration: config.md
  - External Art-Net controller: artnet-controller-communication.md

plugins:
  - search
  - mermaid2
  - awesome-pages
  - mkdocstrings:
      handlers:
        python: {}

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format